CREATE DATABASE PRNProject;
USE PRNProject;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    "Name" NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    "Password" NVARCHAR(255) NOT NULL,
    UserType INT NOT NULL CHECK (UserType IN (1, 2, 3, 4)),
	GroupId INT NOT NULL
);
