CREATE DATABASE PRNProject;
USE PRNProject;

CREATE TABLE Users (
    StudentId NVARCHAR(100) PRIMARY KEY,
    "Name" NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    "Password" NVARCHAR(255) NOT NULL,
    UserType INT NOT NULL CHECK (UserType IN (1, 2, 3, 4)),
	ClubId INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1
);
